steps:
# Install
- name: 'gcr.io/cloud-builders/npm:current'
  args: ['install']
# Test
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['run', 'test']
# Build
- name: 'gcr.io/cloud-builders/npm:current'
  args: ['run', 'build', '--prod']
# Deploy
# - name: 'gcr.io/$PROJECT_ID/firebase'
#   args: ['deploy']
- name: "gcr.io/cloud-builders/gcloud"
  args: ['app', 'deploy', '--version=prod']
timeout: "1600s"